export const mockEmails = [
  {
    id: '1',
    sender: 'NIT DELHI',
    senderEmail: 'sender@example.com',
    subject: 'Action required: unusual login',
    receivedAt: '2m ago',
    score: 92,
    sourceIp: '185.220.101.14',
    geolocation: 'Frankfurt, Germany',
    isp: 'Hetzner Online GmbH',
    whois: 'NameSilo · domain age 17 days',
    abuseScore: 54,
    abuseNote: 'Reported for credential phishing and automated abuse.',
    priorFlagged: '3 of 7 previous emails from this sender were flagged as fraud.',
    preview: 'Your account requires immediate verification. Click below to confirm your identity...',
    lat: 50.1109,
    lng: 8.6821,
  },
  {
    id: '2',
    sender: 'Aditya',
    senderEmail: 'sender@example.com',
    subject: 'Updated Q3 planning notes',
    receivedAt: '18m ago',
    score: 12,
    sourceIp: '203.0.113.5',
    geolocation: 'New Delhi, India',
    isp: 'Reliance Jio',
    whois: 'Known contact · domain age 4 years',
    abuseScore: 0,
    abuseNote: 'No abuse reports found.',
    priorFlagged: '0 of 12 previous emails from this sender were flagged.',
    preview: 'Hi team, attaching the updated planning notes for Q3 review...',
    lat: 28.6139,
    lng: 77.2090,
  },
  {
    id: '3',
    sender: 'Google',
    senderEmail: 'google@google-drive-payments.co',
    subject: 'Invoice #8831 is overdue',
    receivedAt: '1h ago',
    score: 68,
    sourceIp: '198.51.100.22',
    geolocation: 'Bucharest, Romania',
    isp: 'DigitalOcean',
    whois: 'NameCheap · domain age 9 days',
    abuseScore: 38,
    abuseNote: 'Reported for invoice fraud attempts.',
    priorFlagged: '1 of 3 previous emails from this sender were flagged.',
    preview: 'Your CloudDrive invoice is overdue. Verify payment details to avoid suspension...',
    lat: 44.4268,
    lng: 26.1025,
  },
]

export const dashboardStats = {
  totalScanned: 1248,
  scannedChange: '+14% vs prior week',
  totalFlagged: 86,
  flaggedBreakdown: '41 phishing · 45 fraud',
  flaggedRate: '6.9%',
  flaggedRateChange: '−0.8 pts vs prior week',
  riskBreakdown: {
    safe: 1162,
    suspicious: 49,
    high: 37,
  },
}